name: build
run-name: Build Flatpak
on:
  pull_request:
  workflow_dispatch:

jobs:
  Build-Flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            flatpak \
            flatpak-builder \
            icoutils
      - name: Build the flatpak
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_GREP: ${{ secrets.GPG_KEY_GREP }}
        run: |
          ls ${{ github.workspace }}
          chmod +x build.sh
          ./build.sh
