name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Checkout Flatpak repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: flatpak-repository
          path: repo
      - name: Setup GPG
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update -y
          git config --global protocol.file.allow always
          sudo apt-get install --no-install-recommends -y \
            icoutils \
            flatpak \
            flatpak-builder \
            elfutils
      - name: Build Flatpak
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          mkdir -p ./repo
          ./build.sh
      - name: Push Flatpak repository
        run: |
          cd repo
          git add -A
          git commit --signoff -m "Update com.jagexlauncher.JagexLauncher"
          git reset $(git commit-tree HEAD^{tree} -m "Update com.jagexlauncher.JagexLauncher")
          git push --progress -f origin flatpak-repository
        env:
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
